export const clockLetters = () => [
    {letter: 'I', class: ['letter'], rel: 'it is'},
    {letter: 'T', class: ['letter'], rel: 'it is'},
    {letter: 'L', class: ['letter'], rel: ''},
    {letter: 'I', class: ['letter'], rel: 'it is'},
    {letter: 'S', class: ['letter'], rel: 'it is'},
    {letter: 'A', class: ['letter'], rel: ''},
    {letter: 'S', class: ['letter'], rel: ''},
    {letter: 'A', class: ['letter'], rel: ''},
    {letter: 'M', class: ['letter'], rel: ''},
    {letter: 'P', class: ['letter'], rel: ''},
    {letter: 'M', class: ['letter'], rel: ''}, // row 1 end
    {letter: 'A', class: ['letter'], rel: ''},
    {letter: 'C', class: ['letter'], rel: ''},
    {letter: 'Q', class: ['letter'], rel: 'quarter'},
    {letter: 'U', class: ['letter'], rel: 'quarter'},
    {letter: 'A', class: ['letter'], rel: 'quarter'},
    {letter: 'R', class: ['letter'], rel: 'quarter'},
    {letter: 'T', class: ['letter'], rel: 'quarter'},
    {letter: 'E', class: ['letter'], rel: 'quarter'},
    {letter: 'R', class: ['letter'], rel: 'quarter'},
    {letter: 'D', class: ['letter'], rel: ''},
    {letter: 'C', class: ['letter'], rel: ''}, // row 2 end
    {letter: 'T', class: ['letter'], rel: 'twenty'},
    {letter: 'W', class: ['letter'], rel: 'twenty'},
    {letter: 'E', class: ['letter'], rel: 'twenty'},
    {letter: 'N', class: ['letter'], rel: 'twenty'},
    {letter: 'T', class: ['letter'], rel: 'twenty'},
    {letter: 'Y', class: ['letter'], rel: 'twenty'},
    {letter: 'F', class: ['letter'], rel: 'five'},
    {letter: 'I', class: ['letter'], rel: 'five'},
    {letter: 'V', class: ['letter'], rel: 'five'},
    {letter: 'E', class: ['letter'], rel: 'five'},
    {letter: 'X', class: ['letter'], rel: ''}, // row 3 end
    {letter: 'H', class: ['letter'], rel: 'half'},
    {letter: 'A', class: ['letter'], rel: 'half'},
    {letter: 'L', class: ['letter'], rel: 'half'},
    {letter: 'F', class: ['letter'], rel: 'half'},
    {letter: 'S', class: ['letter'], rel: ''},
    {letter: 'T', class: ['letter'], rel: 'ten'},
    {letter: 'E', class: ['letter'], rel: 'ten'},
    {letter: 'N', class: ['letter'], rel: 'ten'},
    {letter: 'F', class: ['letter'], rel: ''},
    {letter: 'T', class: ['letter'], rel: ''},
    {letter: 'O', class: ['letter'], rel: ''}, // row 4 end
    {letter: 'P', class: ['letter'], rel: 'past'},
    {letter: 'A', class: ['letter'], rel: 'past'},
    {letter: 'S', class: ['letter'], rel: 'past'},
    {letter: 'T', class: ['letter'], rel: 'past'},
    {letter: 'E', class: ['letter'], rel: ''},
    {letter: 'R', class: ['letter'], rel: ''},
    {letter: 'U', class: ['letter'], rel: ''},
    {letter: 'N', class: ['letter'], rel: 'nine'},
    {letter: 'I', class: ['letter'], rel: 'nine'},
    {letter: 'N', class: ['letter'], rel: 'nine'},
    {letter: 'E', class: ['letter'], rel: 'nine'}, // row 5 end
    {letter: 'O', class: ['letter'], rel: 'one'},
    {letter: 'N', class: ['letter'], rel: 'one'},
    {letter: 'E', class: ['letter'], rel: 'one'},
    {letter: 'S', class: ['letter'], rel: 'six'},
    {letter: 'I', class: ['letter'], rel: 'six'},
    {letter: 'X', class: ['letter'], rel: 'six'},
    {letter: 'T', class: ['letter'], rel: 'three'},
    {letter: 'H', class: ['letter'], rel: 'three'},
    {letter: 'R', class: ['letter'], rel: 'three'},
    {letter: 'E', class: ['letter'], rel: 'three'},
    {letter: 'E', class: ['letter'], rel: 'three'}, // row 6 end
    {letter: 'F', class: ['letter'], rel: 'four'},
    {letter: 'O', class: ['letter'], rel: 'four'},
    {letter: 'U', class: ['letter'], rel: 'four'},
    {letter: 'R', class: ['letter'], rel: 'four'},
    {letter: 'F', class: ['letter'], rel: 'five'},
    {letter: 'I', class: ['letter'], rel: 'five'},
    {letter: 'V', class: ['letter'], rel: 'five'},
    {letter: 'E', class: ['letter'], rel: 'five'},
    {letter: 'T', class: ['letter'], rel: 'two'},
    {letter: 'W', class: ['letter'], rel: 'two'},
    {letter: 'O', class: ['letter'], rel: 'two'}, // row 7 end
    {letter: 'E', class: ['letter'], rel: 'eight'},
    {letter: 'I', class: ['letter'], rel: 'eight'},
    {letter: 'G', class: ['letter'], rel: 'eight'},
    {letter: 'H', class: ['letter'], rel: 'eight'},
    {letter: 'T', class: ['letter'], rel: 'eight'},
    {letter: 'E', class: ['letter'], rel: 'eleven'},
    {letter: 'L', class: ['letter'], rel: 'eleven'},
    {letter: 'E', class: ['letter'], rel: 'eleven'},
    {letter: 'V', class: ['letter'], rel: 'eleven'},
    {letter: 'E', class: ['letter'], rel: 'eleven'},
    {letter: 'N', class: ['letter'], rel: 'eleven'}, // row 8 end
    {letter: 'S', class: ['letter'], rel: 'seven'},
    {letter: 'E', class: ['letter'], rel: 'seven'},
    {letter: 'V', class: ['letter'], rel: 'seven'},
    {letter: 'E', class: ['letter'], rel: 'seven'},
    {letter: 'N', class: ['letter'], rel: 'seven'},
    {letter: 'T', class: ['letter'], rel: 'twelve'},
    {letter: 'W', class: ['letter'], rel: 'twelve'},
    {letter: 'E', class: ['letter'], rel: 'twelve'},
    {letter: 'L', class: ['letter'], rel: 'twelve'},
    {letter: 'V', class: ['letter'], rel: 'twelve'},
    {letter: 'E', class: ['letter'], rel: 'twelve'}, // row 9 end
    {letter: 'T', class: ['letter'], rel: 'ten'},
    {letter: 'E', class: ['letter'], rel: 'ten'},
    {letter: 'N', class: ['letter'], rel: 'ten'},
    {letter: 'S', class: ['letter'], rel: ''},
    {letter: 'E', class: ['letter'], rel: ''},
    {letter: 'O\'', class: ['letter'], rel: 'oclock'},
    {letter: 'C', class: ['letter'], rel: 'oclock'},
    {letter: 'L', class: ['letter'], rel: 'oclock'},
    {letter: 'O', class: ['letter'], rel: 'oclock'},
    {letter: 'C', class: ['letter'], rel: 'oclock'},
    {letter: 'K', class: ['letter'], rel: 'oclock'}, // row 10 end
]