export const clockLetters = () => [
    {letter: 'I', type: 'obligatory', class: ['letter'], rel: 'it is'},
    {letter: 'T', type: 'obligatory', class: ['letter'], rel: 'it is'},
    {letter: 'L', type: '', class: ['letter'], rel: ''},
    {letter: 'I', type: 'obligatory', class: ['letter'], rel: 'it is'},
    {letter: 'S', type: 'obligatory', class: ['letter'], rel: 'it is'},
    {letter: 'A', type: '', class: ['letter'], rel: ''},
    {letter: 'S', type: '', class: ['letter'], rel: ''},
    {letter: 'A', type: '', class: ['letter'], rel: ''},
    {letter: 'M', type: '', class: ['letter'], rel: ''},
    {letter: 'P', type: '', class: ['letter'], rel: ''},
    {letter: 'M', type: '', class: ['letter'], rel: ''}, // row 1 end
    {letter: 'A', type: '', class: ['letter'], rel: ''},
    {letter: 'C', type: '', class: ['letter'], rel: ''},
    {letter: 'Q', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'U', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'A', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'R', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'T', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'E', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'R', type: 'minute', class: ['letter'], rel: 15},
    {letter: 'D', type: '', class: ['letter'], rel: ''},
    {letter: 'C', type: '', class: ['letter'], rel: ''}, // row 2 end
    {letter: 'T', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'W', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'E', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'N', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'T', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'Y', type: 'minute', class: ['letter'], rel: 20},
    {letter: 'F', type: 'minute', class: ['letter'], rel: 5},
    {letter: 'I', type: 'minute', class: ['letter'], rel: 5},
    {letter: 'V', type: 'minute', class: ['letter'], rel: 5},
    {letter: 'E', type: 'minute', class: ['letter'], rel: 5},
    {letter: 'X', type: 'minute', class: ['letter'], rel: ''}, // row 3 end
    {letter: 'H', type: 'minute', class: ['letter'], rel: 30},
    {letter: 'A', type: 'minute', class: ['letter'], rel: 30},
    {letter: 'L', type: 'minute', class: ['letter'], rel: 30},
    {letter: 'F', type: 'minute', class: ['letter'], rel: 30},
    {letter: 'S', type: '', class: ['letter'], rel: ''},
    {letter: 'T', type: 'minute', class: ['letter'], rel: 10},
    {letter: 'E', type: 'minute', class: ['letter'], rel: 10},
    {letter: 'N', type: 'minute', class: ['letter'], rel: 10},
    {letter: 'F', type: '', class: ['letter'], rel: ''},
    {letter: 'T', type: '', class: ['letter'], rel: ''},
    {letter: 'O', type: '', class: ['letter'], rel: ''}, // row 4 end
    {letter: 'P', type: '', class: ['letter'], rel: 'past'},
    {letter: 'A', type: '', class: ['letter'], rel: 'past'},
    {letter: 'S', type: '', class: ['letter'], rel: 'past'},
    {letter: 'T', type: '', class: ['letter'], rel: 'past'},
    {letter: 'E', type: '', class: ['letter'], rel: ''},
    {letter: 'R', type: '', class: ['letter'], rel: ''},
    {letter: 'U', type: '', class: ['letter'], rel: ''},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 9},
    {letter: 'I', type: 'hour', class: ['letter'], rel: 9},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 9},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 9}, // row 5 end
    {letter: 'O', type: 'hour', class: ['letter'], rel: 1},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 1},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 1},
    {letter: 'S', type: 'hour', class: ['letter'], rel: 6},
    {letter: 'I', type: 'hour', class: ['letter'], rel: 6},
    {letter: 'X', type: 'hour', class: ['letter'], rel: 6},
    {letter: 'T', type: 'hour', class: ['letter'], rel: 3},
    {letter: 'H', type: 'hour', class: ['letter'], rel: 3},
    {letter: 'R', type: 'hour', class: ['letter'], rel: 3},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 3},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 3}, // row 6 end
    {letter: 'F', type: 'hour', class: ['letter'], rel: 4},
    {letter: 'O', type: 'hour', class: ['letter'], rel: 4},
    {letter: 'U', type: 'hour', class: ['letter'], rel: 4},
    {letter: 'R', type: 'hour', class: ['letter'], rel: 4},
    {letter: 'F', type: 'hour', class: ['letter'], rel: 5},
    {letter: 'I', type: 'hour', class: ['letter'], rel: 5},
    {letter: 'V', type: 'hour', class: ['letter'], rel: 5},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 5},
    {letter: 'T', type: 'hour', class: ['letter'], rel: 2},
    {letter: 'W', type: 'hour', class: ['letter'], rel: 2},
    {letter: 'O', type: 'hour', class: ['letter'], rel: 2}, // row 7 end
    {letter: 'E', type: 'hour', class: ['letter'], rel: 8},
    {letter: 'I', type: 'hour', class: ['letter'], rel: 8},
    {letter: 'G', type: 'hour', class: ['letter'], rel: 8},
    {letter: 'H', type: 'hour', class: ['letter'], rel: 8},
    {letter: 'T', type: 'hour', class: ['letter'], rel: 8},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 11},
    {letter: 'L', type: 'hour', class: ['letter'], rel: 11},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 11},
    {letter: 'V', type: 'hour', class: ['letter'], rel: 11},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 11},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 11}, // row 8 end
    {letter: 'S', type: 'hour', class: ['letter'], rel: 7},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 7},
    {letter: 'V', type: 'hour', class: ['letter'], rel: 7},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 7},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 7},
    {letter: 'T', type: 'hour', class: ['letter'], rel: 12},
    {letter: 'W', type: 'hour', class: ['letter'], rel: 12},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 12},
    {letter: 'L', type: 'hour', class: ['letter'], rel: 12},
    {letter: 'V', type: 'hour', class: ['letter'], rel: 12},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 12}, // row 9 end
    {letter: 'T', type: 'hour', class: ['letter'], rel: 10},
    {letter: 'E', type: 'hour', class: ['letter'], rel: 10},
    {letter: 'N', type: 'hour', class: ['letter'], rel: 10},
    {letter: 'S', type: '', class: ['letter'], rel: ''},
    {letter: 'E', type: '', class: ['letter'], rel: ''},
    {letter: 'O\'', type: 'obligatory', class: ['letter'], rel: 'oclock'},
    {letter: 'C', type: 'obligatory', class: ['letter'], rel: 'oclock'},
    {letter: 'L', type: 'obligatory', class: ['letter'], rel: 'oclock'},
    {letter: 'O', type: 'obligatory', class: ['letter'], rel: 'oclock'},
    {letter: 'C', type: 'obligatory', class: ['letter'], rel: 'oclock'},
    {letter: 'K', type: 'obligatory', class: ['letter'], rel: 'oclock'}, // row 10 end
]